Algoritmo "AreaPentagono"
Var
  perimetro, apotema, area : real

Inicio

  Escreval("Calculadora da área de pentagono regular")
  Escreval("")
  Escreva("Digite o valor do perimetro do pentago: ")
  Leia (perimetro)
  Escreva("Digite o valor da apótema do pentago: ")
  Leia (apotema)
  area <- 1/2 * perimetro * apotema
  Escreva("O valor do perimetro do pentago é: ", area)
Fimalgoritmo
